name: Blank

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build # This job is needed to satisfy kodiak
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
