name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run checks
      run: |
        make ci
